# Generated by Django 5.2.9 on 2025-12-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="HallComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_components",
                        to="halls.hall",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="halls.hallcomponent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "hallcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="halls.hallcomponent",
                    ),
                ),
                ("number", models.IntegerField()),
                ("is_vip", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Seat",
            },
            bases=("halls.hallcomponent",),
        ),
        migrations.CreateModel(
            name="SeatGroup",
            fields=[
                (
                    "hallcomponent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="halls.hallcomponent",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Seat Group (Row/Sector)",
            },
            bases=("halls.hallcomponent",),
        ),
    ]
