# Generated by Django 5.2.9 on 2025-12-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("halls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seatgroup",
            options={"verbose_name": "Seat Group"},
        ),
        migrations.RemoveField(
            model_name="seat",
            name="is_vip",
        ),
        migrations.AddField(
            model_name="seat",
            name="seat_type",
            field=models.CharField(
                choices=[("STD", "Standard"), ("VIP", "VIP"), ("BLC", "Balcony")],
                default="STD",
                max_length=3,
            ),
        ),
    ]
